use_frameworks!

platform :ios, '8.0'

target 'ExEmitterView_Example' do
  pod 'ExEmitterView', :path => '../'
  
  pod "ExMVVMKit",:path => "../../ExMVVMKit/ExMVVMKit.podspec"
  pod 'SDWebImage'

  target 'ExEmitterView_Tests' do
    inherit! :search_paths

  end
end
